---
# handlers for ansible-role-systemd-networkd

- name: restart systemd-networkd
  become: true
  service:
    name: systemd-networkd
    state: restarted
  when: systemd_networkd_apply_config

- name: Restart systemd-resolved
  become: true
  service:
    name: systemd-resolved
    state: restarted
